import { ArrowRight } from "lucide-react"
import { delhiDemandProject, forecastPoints } from "../../../data/delhi-electricity-demand-forecasting/project-data"

function ForecastChart() {
  const toPoints = (key: "actual" | "predicted") => forecastPoints.map((point, index) => `${(index / (forecastPoints.length - 1)) * 100},${92 - ((point[key] - 3000) / 2500) * 78}`).join(" ")
  return <div className="delhi-chart" role="img" aria-label="Actual demand compared with predicted demand over a representative forecast period"><div className="delhi-chart__legend"><span><i className="legend-actual" /> ACTUAL DEMAND</span><span><i className="legend-predicted" /> PREDICTED DEMAND</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path className="chart-grid" d="M0 20H100M0 45H100M0 70H100M0 95H100M25 0V100M50 0V100M75 0V100" /><polyline className="chart-line chart-line--actual" points={toPoints("actual")} /><polyline className="chart-line chart-line--predicted" points={toPoints("predicted")} />{[4, 12].map((index) => <circle key={index} className="chart-peak" cx={(index / 15) * 100} cy={92 - ((forecastPoints[index].actual - 3000) / 2500) * 78} r="1.5" />)}</svg><div className="delhi-chart__axis"><span>HISTORICAL LOAD</span><span>1 HOUR AHEAD</span></div></div>
}

export function ProjectHero() {
  return <section className="delhi-section delhi-hero"><div className="delhi-shell delhi-hero__grid"><div className="delhi-hero__copy"><p className="delhi-kicker">01 / TIME SERIES / MACHINE LEARNING</p><h1>Delhi Electricity<br />Demand Forecasting</h1><p className="delhi-lede">Forecasting Delhi's short-term electricity demand from historical load patterns using leakage-safe time-series machine learning.</p><div className="delhi-actions"><a className="delhi-button delhi-button--primary" href={delhiDemandProject.demoUrl}>VIEW LIVE DEMO <ArrowRight aria-hidden="true" size={16} /></a><span className="delhi-button delhi-button--disabled">VIEW SOURCE CODE <span>URL NOT CONFIGURED</span></span></div></div><div className="delhi-hero__visual"><div className="delhi-visual__top"><span>ACTUAL VS PREDICTED</span><span>MW / HOURLY</span></div><ForecastChart /></div></div><div className="delhi-shell delhi-meta-grid">{delhiDemandProject.metadata.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section>
}
