import { useState } from "react"
import { ArrowLeft, ArrowRight, Check, LoaderCircle, Search, TriangleAlert } from "lucide-react"
import { evBatteryDemoConfig as config } from "../../../../data/ev-battery-failure/demo-config"
import type { BatteryPredictionResponse, BatteryRecord, PredictionStatus } from "../../../../types/ev-battery-demo"
import { getBatteryRecord, getFailureExample, getHealthyExample, predictBattery } from "../../../../services/ev-battery-failure/ev-battery-api"
import "./ev-battery-failure-demo.css"

const telemetryFields: Array<[keyof NonNullable<BatteryRecord["telemetry"]>, string]> = [["battery_health", "BATTERY HEALTH"], ["state_of_health", "STATE OF HEALTH"], ["capacity_loss", "CAPACITY LOSS"], ["cycle_count", "CYCLE COUNT"], ["internal_resistance", "INTERNAL RESISTANCE"], ["thermal_runaway_risk", "THERMAL RUNAWAY RISK"], ["bms_warning_count", "BMS WARNING COUNT"], ["maintenance_score", "MAINTENANCE SCORE"]]
const formatValue = (value: unknown) => typeof value === "number" ? Number.isInteger(value) ? value.toLocaleString() : value.toFixed(2) : String(value ?? "—")

function DemoHeader({ available }: { available: boolean }) { return <header className="ev-demo-header ev-demo-shell"><nav><a href={config.caseStudyUrl}><ArrowLeft size={14} /> BACK TO CASE STUDY</a><span>PROJECT / EV BATTERY FAILURE / LIVE MODEL</span></nav><p className="ev-demo-kicker">LIVE MODEL / TABULAR CLASSIFICATION</p><h1>Test the Battery<br /><span>Failure Model</span></h1><p className="ev-demo-description">Select an EV battery record and run the trained model to estimate its failure probability.</p><div className="ev-demo-meta"><span>MODEL <b>{config.model}</b></span><span>STATUS <b className={available ? "is-ready" : "is-unavailable"}>● {available ? "AVAILABLE" : "UNAVAILABLE"}</b></span><span>INPUT FEATURES <b>{config.inputFeatures}</b></span></div></header> }

function BatterySelector({ row, loading, onExample, onRow, onRowChange, error }: { row: string; loading: boolean; onExample: (kind: "healthy" | "failure") => void; onRow: () => void; onRowChange: (value: string) => void; error: string | null }) { return <div className="ev-selector"><div className="ev-console-heading"><span>01 / INPUT</span><h2>BATTERY RECORD</h2></div><div className="ev-presets"><span>LOAD VERIFIED DATASET EXAMPLE</span><div><button type="button" onClick={() => onExample("healthy")} disabled={loading}>LOAD HEALTHY EXAMPLE</button><button type="button" onClick={() => onExample("failure")} disabled={loading}>LOAD FAILURE EXAMPLE</button></div></div><label className="ev-row-field" htmlFor="battery-row"><span>BATTERY ROW</span><div><input id="battery-row" inputMode="numeric" value={row} onChange={event => onRowChange(event.target.value)} placeholder="e.g. 1042" /><button type="button" onClick={onRow} disabled={loading}><Search size={15} /> LOAD ROW</button></div><small>Enter a valid row from the available dataset.</small></label>{error && <div className="ev-inline-error" role="alert"><TriangleAlert size={15} /><div><strong>{error === "RECORD_NOT_FOUND" ? "BATTERY RECORD NOT FOUND" : error === "INVALID_ROW" ? "INVALID BATTERY ROW" : "RECORD UNAVAILABLE"}</strong><span>{error === "RECORD_NOT_FOUND" ? "Choose another row." : "Choose a battery record before running inference."}</span></div></div>}</div> }

function BatteryTelemetry({ record }: { record: BatteryRecord }) { return <div className="ev-telemetry"><div className="ev-telemetry-head"><span>SELECTED RECORD</span><b>ROW {record.row}</b></div><div className="ev-telemetry-grid">{telemetryFields.map(([key, label]) => <div key={key}><span>{label}</span><strong>{formatValue(record.telemetry[key])}{typeof record.telemetry[key] === "number" && key !== "cycle_count" && key !== "bms_warning_count" ? " %" : ""}</strong></div>)}</div><p>TELEMETRY CONTEXT · VALUES RETURNED BY THE DATASET SERVICE</p></div> }

function ProbabilityRail({ probability }: { probability: number }) { const safe = Math.max(0, Math.min(1, probability)); return <div className="ev-probability"><div className="ev-probability-label"><span>MODEL FAILURE PROBABILITY</span><b>{(safe * 100).toFixed(2)}%</b></div><div className="ev-rail" role="img" aria-label={`Failure probability ${(safe * 100).toFixed(2)} percent. Decision threshold 50 percent.`}><i style={{ left: `${safe * 100}%` }} /><b /></div><div className="ev-rail-scale"><span>0% HEALTHY</span><span>50% DECISION THRESHOLD</span><span>100% FAILURE</span></div><small>MODEL SCORE · The displayed probability is the classifier&apos;s model output and should not be interpreted as a calibrated real world battery failure probability.</small></div> }

function PredictionPanel({ status, prediction, record, error }: { status: PredictionStatus; prediction: BatteryPredictionResponse | null; record: BatteryRecord | null; error: string | null }) { if (status === "idle") return <div className="ev-prediction"><div className="ev-console-heading"><span>02 / PREDICTION</span><h2>MODEL OUTPUT</h2></div><div className="ev-awaiting"><strong>AWAITING BATTERY</strong><p>Select a battery record and run the model.</p></div></div>; if (status === "loading") return <div className="ev-prediction"><div className="ev-console-heading"><span>02 / PREDICTION</span><h2>MODEL OUTPUT</h2></div><div className="ev-awaiting"><LoaderCircle className="ev-loader" size={19} /><strong>ANALYZING BATTERY RECORD...</strong><p>RUNNING SAVED ML PIPELINE</p></div></div>; if (status === "error") return <div className="ev-prediction"><div className="ev-console-heading"><span>02 / PREDICTION</span><h2>MODEL OUTPUT</h2></div><div className="ev-result-error" role="alert"><strong>{error === "MODEL_SERVICE_UNAVAILABLE" ? "MODEL UNAVAILABLE" : "PREDICTION UNAVAILABLE"}</strong><p>{error === "MODEL_SERVICE_UNAVAILABLE" ? "The inference service could not be reached. Try again shortly." : error === "RECORD_NOT_FOUND" ? "Battery record not found. Choose another row." : "Unable to run this battery record."}</p></div></div>; if (!prediction || !record) return null; const correct = prediction.correct ?? (prediction.actual_label === record.actual_label && prediction.prediction === record.actual_label); const failure = prediction.prediction === "Failure"; return <div className="ev-prediction" aria-live="polite"><div className="ev-console-heading"><span>02 / PREDICTION · COMPLETE</span><h2>MODEL OUTPUT</h2></div><div className={`ev-result ev-result--${failure ? "failure" : "healthy"}`}><span>PREDICTION</span><strong>{failure ? "BATTERY FAILURE RISK" : "BATTERY HEALTHY"}</strong><b>{(prediction.failure_probability * 100).toFixed(2)}%</b><small>MODEL FAILURE PROBABILITY</small></div><ProbabilityRail probability={prediction.failure_probability} /><div className="ev-actual"><div><span>ACTUAL LABEL</span><strong>{prediction.actual_label ?? record.actual_label}</strong></div><div className={`ev-correct ${correct ? "is-correct" : "is-incorrect"}`}><span>MODEL RESULT</span><strong>{correct ? <><Check size={14} /> CORRECT</> : "INCORRECT"}</strong></div></div></div> }

function ModelEvidence() { return <section className="ev-evidence ev-demo-shell"><div className="ev-evidence-heading"><div><p className="ev-demo-kicker">MODEL EVIDENCE</p><h2>One model, measured on the failure class.</h2></div><a href={config.caseStudyUrl}>HOW WAS THIS MODEL SELECTED? <ArrowRight size={14} /><br /><b>VIEW CASE STUDY</b></a></div><div className="ev-evidence-strip">{[[config.model, "FINAL MODEL"], [config.failureRecall, "TEST FAILURE RECALL"], [config.prAuc, "PR AUC"], [config.testFailures, "TEST FAILURES"], [config.missedFailures, "MISSED FAILURES"]].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="ev-synthetic"><span>SYNTHETIC DATASET</span><p>This demo uses records from a synthetic EV battery dataset. Predictions demonstrate the trained machine learning workflow and should not be interpreted as validated real world battery diagnostics.</p></div></section> }

function ModelWorkbench() { const available = Boolean(import.meta.env.VITE_EV_BATTERY_API_URL); const [record, setRecord] = useState<BatteryRecord | null>(null); const [row, setRow] = useState(""); const [status, setStatus] = useState<PredictionStatus>("idle"); const [prediction, setPrediction] = useState<BatteryPredictionResponse | null>(null); const [error, setError] = useState<string | null>(null); async function load(loader: () => Promise<BatteryRecord>) { setStatus("loading"); setError(null); setPrediction(null); try { const next = await loader(); setRecord(next); setRow(String(next.row)); setStatus("idle") } catch (caught) { setRecord(null); setStatus("error"); setError(caught instanceof Error ? caught.message : "RECORD_UNAVAILABLE") } } async function loadRow() { if (!/^\d+$/.test(row)) { setError("INVALID_ROW"); return } await load(() => getBatteryRecord(Number(row))) } async function run() { if (!record) { setError("NO_RECORD"); return } setStatus("loading"); setError(null); try { const result = await predictBattery(record); setPrediction({ ...result, actual_label: result.actual_label ?? record.actual_label, row: result.row ?? record.row }); setStatus("success") } catch (caught) { setStatus("error"); setError(caught instanceof Error ? caught.message : "INFERENCE_ERROR") } } return <><DemoHeader available={available} /><main className="ev-demo-shell ev-workbench"><div className="ev-workbench-status"><span>ONE WORKSPACE · RECORD → MODEL → PREDICTION</span><strong className={!available || status === "error" ? "is-unavailable" : ""}>{!available || status === "error" ? "UNAVAILABLE" : status === "loading" ? "RUNNING" : "READY"}</strong></div><div className="ev-workbench-grid"><section className="ev-input-panel"><BatterySelector row={row} loading={status === "loading"} onExample={kind => load(kind === "healthy" ? getHealthyExample : getFailureExample)} onRow={loadRow} onRowChange={setRow} error={error} />{record && <><BatteryTelemetry record={record} /><button className="ev-run" type="button" disabled={status === "loading"} onClick={run}>RUN FAILURE PREDICTION <ArrowRight size={15} /></button></>}</section><PredictionPanel status={status} prediction={prediction} record={record} error={error} /></div></main><ModelEvidence /></> }

export function EVBatteryFailureDemoPage() { return <main className="ev-battery-demo"><ModelWorkbench /></main> }
