import { ArrowDown } from "lucide-react"
import { experimentMetrics } from "../../../data/emotion-detection/project-data"

const baseline = ["RAW TEXT", "TF-IDF", "30K FEATURES", "LOGISTIC REGRESSION"]
const transformer = ["RAW TEXT", "DISTILBERT TOKENIZER", "TOKEN IDS + ATTENTION MASK", "PRETRAINED DISTILBERT", "FINE-TUNED CLASSIFICATION HEAD"]

function Pipeline({ title, steps, metrics, accent }: { title: string; steps: string[]; metrics: readonly (readonly [string, string])[]; accent?: boolean }) { return <article className={`emotion-pipeline-card ${accent ? "is-accent" : ""}`}><div className="emotion-pipeline-title"><span>{title}</span><b>{accent ? "CONTEXTUAL" : "SPARSE"}</b></div><div className="emotion-pipeline-steps">{steps.map((step, index) => <div key={step}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong>{index < steps.length - 1 && <ArrowDown size={14} />}</div>)}</div><div className="emotion-pipeline-metrics">{metrics.map(([label, value]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></article> }

export function ExperimentDesignSection() { return <section className="emotion-section emotion-experiment"><div className="emotion-shell"><div className="emotion-section-heading"><p className="emotion-kicker">03 / EXPERIMENT DESIGN</p><h2>FROM SPARSE FEATURES<br />TO CONTEXTUAL REPRESENTATIONS</h2></div><div className="emotion-pipeline-grid"><Pipeline title="TRADITIONAL NLP" steps={baseline} metrics={experimentMetrics.baseline} /><Pipeline title="TRANSFORMER" steps={transformer} metrics={experimentMetrics.transformer} accent /></div><div className="emotion-reasoning"><div><span>TF-IDF + LOGISTIC REGRESSION</span><p>A fast, interpretable baseline for high-dimensional sparse text features. It establishes whether Transformer complexity produces meaningful improvement.</p></div><div><span>DISTILBERT</span><p>Selected as a lightweight pretrained Transformer that provides contextual representations while remaining practical for local fine-tuning.</p></div></div></div></section> }
