import { ArrowDown, ArrowLeft, ArrowRight, Check, ExternalLink, GitBranch, ShieldAlert, Zap } from "lucide-react"
import { Header } from "../../../sections/Header"
import { evBatteryDomains, evBatteryFailureData as d } from "../../../data/ev-battery-failure/project-data"
import "./ev-battery-failure.css"

const Button = ({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) => <a className={`battery-button ${secondary ? "battery-button--secondary" : ""}`} href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noopener noreferrer" : undefined}>{children}</a>

function ProjectHero() {
  return <section className="battery-hero battery-shell"><div className="battery-hero-copy"><p className="battery-kicker">PROJECT / MACHINE LEARNING</p><h1>EV Battery<br /><span>Failure Prediction</span></h1><p className="battery-lede">Predicting battery failure risk from vehicle, battery, charging, driving, environmental, maintenance and diagnostic data.</p><div className="battery-tags">{["PYTHON", "SCIKIT LEARN", "PANDAS", "STREAMLIT", "LOGISTIC REGRESSION"].map(tag => <span key={tag}>{tag}</span>)}</div><div className="battery-actions"><Button href="/projects/ev-battery-failure/demo">VIEW LIVE DEMO <ArrowRight size={15} /></Button><Button href={d.github} secondary>VIEW SOURCE CODE <ExternalLink size={14} /></Button></div></div><div className="battery-hero-art"><div className="battery-art-top"><span>FAILURE RISK / CLASSIFIER</span><span>LIVE ARTIFACT</span></div><div className="battery-schematic"><div className="battery-cell"><span>EV BATTERY</span><div className="battery-cell-body"><i /><i /><i /><i /><i /><i /></div><small>TELEMETRY INPUT</small></div><div className="battery-flow"><ArrowDown size={15} /><span>FEATURE<br />SIGNALS</span><ArrowDown size={15} /></div><div className="battery-risk"><span>MODEL OUTPUT</span><strong>FAILURE RISK</strong><b>0.9767</b><small>VERIFIED INFERENCE EXAMPLE</small></div></div><div className="battery-traces"><i /><i /><i /><i /><i /><i /><i /></div><div className="battery-annotations"><span>HEALTH</span><span>THERMAL</span><span>CHARGING</span><span>BMS</span></div></div><div className="battery-metric-strip">{d.metrics.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section>
}

function ProblemDataSection() {
  return <section className="battery-section battery-problem"><div className="battery-shell"><div className="battery-section-heading"><p className="battery-kicker">02 / PROBLEM + DATA</p><h2>Failure detection is an imbalanced risk problem.</h2><p>Identify batteries showing failure risk while paying particular attention to false negatives. A missed failure is more important than simply maximizing overall accuracy.</p></div><div className="battery-problem-grid"><div className="battery-problem-callout"><ShieldAlert size={21} /><span>OBJECTIVE</span><strong>Catch the failure<br /><em>before it is missed.</em></strong><p>Failure cases represent only ~9.96% of the dataset, so the model must be evaluated on the minority class rather than accuracy alone.</p></div><div className="battery-data-panel"><div className="battery-data-stats">{d.dataset.map(([value,label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="battery-balance"><div><span>HEALTHY</span><b>~90.04%</b><i style={{ width: "90.04%" }} /></div><div><span>FAILURE</span><b>~9.96%</b><i style={{ width: "9.96%" }} /></div></div></div></div><div className="battery-data-foot"><div><span>TARGET</span><strong>battery_failure</strong><small>0 = Healthy &nbsp;&nbsp; 1 = Failure</small></div><div><span>DATASET NOTE</span><strong>SYNTHETIC DATA</strong><p>The dataset is synthetic. Results demonstrate the machine learning methodology used in this project and should not be interpreted as validated real world EV fleet performance.</p></div><div className="battery-domain-list"><span>FEATURE DOMAINS</span><div>{evBatteryDomains.map(domain => <b key={domain}>{domain}</b>)}</div></div></div></div></section>
}

function DataSignalsSection() {
  return <section className="battery-section battery-signals"><div className="battery-shell"><div className="battery-section-heading battery-heading-split"><div><p className="battery-kicker">03 / SIGNALS IN THE DATA</p><h2>Failure cases showed a consistent degradation pattern.</h2></div><p>Four of the clearest observed comparisons point to the same story: degradation, thermal stress and operational load accumulate together.</p></div><div className="battery-signals-grid">{d.signals.map(([label, healthy, failure]) => <article key={label}><div className="battery-signal-head"><span>{label}</span><Zap size={15} /></div><div className="battery-signal-bars"><div><b style={{ width: `${label === "CYCLE COUNT" ? 34 : label === "THERMAL RUNAWAY RISK" ? 65 : Number.parseFloat(healthy) || 44}%` }} /><span>{healthy}</span><small>HEALTHY</small></div><div className="is-failure"><b style={{ width: `${label === "CYCLE COUNT" ? 100 : label === "THERMAL RUNAWAY RISK" ? 100 : Number.parseFloat(failure) || 65}%` }} /><span>{failure}</span><small>FAILURE</small></div></div></article>)}</div><div className="battery-observations"><div><span>FAILED BATTERIES ALSO SHOWED</span><ul>{["↑ Internal resistance", "↑ Fast charging", "↑ Overcharge events", "↑ Charging interruptions", "↓ Maintenance scores", "↓ Cooling system health", "↑ BMS warnings", "↑ Voltage imbalance"].map(item => <li key={item}>{item}</li>)}</ul></div><strong>BATTERY DEGRADATION <b>+</b> CHARGING STRESS <b>+</b> DIAGNOSTIC WARNINGS <ArrowRight size={17} /> FAILURE SIGNALS</strong></div></div></section>
}

function MLApproachSection() {
  const steps = [["01", "RAW EV DATA"], ["02", "TRAIN / TEST SPLIT"], ["03", "PREPROCESSING"], ["04", "CLASS WEIGHTING"], ["05", "MODEL COMPARISON"], ["06", "FAILURE PROBABILITY"]]
  return <section className="battery-section battery-approach"><div className="battery-shell"><div className="battery-section-heading"><p className="battery-kicker">04 / ML APPROACH</p><h2>From raw EV data to failure probability.</h2><p>A transparent pipeline keeps the modeling choices visible, from leakage control to the final metric trade off.</p></div><div className="battery-pipeline">{steps.map(([num,label], index) => <div className="battery-pipeline-step" key={num}><span>{num}</span><strong>{label}</strong>{index < steps.length - 1 && <ArrowRight size={15} />}</div>)}</div><div className="battery-approach-grid"><div><span>PREPROCESSING</span><div className="battery-preprocess"><article><b>NUMERICAL</b><strong>Median Imputation <ArrowRight size={14} /> StandardScaler</strong></article><article><b>CATEGORICAL</b><strong>Most Frequent Imputation <ArrowRight size={14} /> One Hot Encoding</strong></article></div><p className="battery-note">IDENTIFIERS REMOVED &nbsp; vehicle_id &nbsp; / &nbsp; battery_serial</p></div><div className="battery-split"><span>SPLIT + IMBALANCE</span><div><b>TRAIN <strong>80%</strong></b><b>TEST <strong>20%</strong></b><b>STRATIFIED <strong>BY TARGET</strong></b></div><strong className="battery-balanced">class_weight=&quot;balanced&quot;</strong></div></div><div className="battery-leakage"><GitBranch size={17} /><div><span>LEAKAGE CONTROL</span><p>The train/test split was performed before fitting preprocessing so information from the test set could not leak into the training transformations.</p></div></div></div></section>
}

function ConfusionMatrix() { return <div className="battery-matrix-wrap"><div className="battery-matrix-label">CONFUSION MATRIX / TEST SET</div><div className="battery-matrix"><div /><b>PREDICTED<br /><span>HEALTHY &nbsp;&nbsp;&nbsp; FAILURE</span></b><strong>ACTUAL<br /><span>HEALTHY</span></strong><div className="matrix-tn">33,812<small>TRUE NEGATIVE</small></div><div className="matrix-fp">2,204<small>FALSE POSITIVE</small></div><strong><span>FAILURE</span></strong><div className="matrix-fn">164<small>FALSE NEGATIVE</small></div><div className="matrix-tp">3,820<small>TRUE POSITIVE</small></div></div></div> }

function ModelComparisonSection() {
  return <section className="battery-section battery-comparison"><div className="battery-shell"><div className="battery-section-heading battery-heading-split"><div><p className="battery-kicker">05 / MODEL COMPARISON + DECISION</p><h2>The selected model did not win every metric.</h2></div><p>It won the metric that mattered most for this failure detection objective: the failure recall and false negative trade off.</p></div><div className="battery-model-table"><table><caption>Failure classification benchmark</caption><thead><tr><th>MODEL</th><th>FAILURE<br />PRECISION</th><th>FAILURE<br />RECALL</th><th>FAILURE<br />F1</th><th>ROC AUC</th><th>PR AUC</th></tr></thead><tbody>{d.models.map(([name, precision, recall, f1, roc, pr]) => <tr className={name === "Logistic Regression" ? "is-selected" : ""} key={name}><th>{name}{name === "Logistic Regression" && <small>SELECTED MODEL</small>}</th><td>{precision}</td><td>{recall}</td><td>{f1}</td><td>{roc}</td><td>{pr}</td></tr>)}</tbody></table></div><div className="battery-fn-grid"><div><span>RANDOM FOREST</span><strong>633</strong><b>FALSE NEGATIVES</b></div><div><span>HISTGRADIENTBOOSTING</span><strong>213</strong><b>FALSE NEGATIVES</b></div><div className="is-selected"><span>LOGISTIC REGRESSION</span><strong>164</strong><b>FALSE NEGATIVES</b></div></div><div className="battery-decision"><div><p>For a failure detection system, missing an actual failure was treated as a more serious error than generating additional false alarms.</p><p>Logistic Regression therefore became the selected model because it reduced false negatives to <strong>164</strong> while retaining <strong>96% failure recall</strong> and strong ranking performance.</p></div><div className="battery-decision-metrics"><b><strong>96%</strong>FAILURE RECALL</b><b><strong>0.9893</strong>ROC AUC</b><b><strong>0.9222</strong>PR AUC</b></div></div><ConfusionMatrix /><div className="battery-sensitivity"><div><p className="battery-kicker">SENSITIVITY CHECK</p><h3>Do derived features explain the score?</h3><p>Six engineered derived features were removed and Logistic Regression was retrained.</p></div><div className="battery-sensitivity-compare"><article><span>ORIGINAL</span><b>0.9222 <small>PR AUC</small></b><b>~96% <small>FAILURE RECALL</small></b></article><ArrowRight size={16} /><article><span>WITHOUT DERIVED FEATURES</span><b>0.9149 <small>PR AUC</small></b><b>~96% <small>FAILURE RECALL</small></b></article></div></div><div className="battery-limit"><span>INTERPRETATION LIMIT</span><p>Because the dataset is synthetic and diagnostic variables participated in target generation, the very strong discrimination metrics must still be interpreted cautiously.</p></div></div></section>
}

function ResultShipSection() { return <section className="battery-section battery-ship"><div className="battery-shell"><div className="battery-ship-panel"><div className="battery-section-heading"><p className="battery-kicker">06 / RESULT + SHIP</p><h2>From experiment to usable inference.</h2><p>The project ships the trained artifact, an inference script and a Streamlit prediction interface that returns a class and failure probability.</p></div><div className="battery-deliverables">{[["TRAINED MODEL", "ev_battery_failure_logistic.joblib"], ["INFERENCE", "src/predict.py"], ["LIVE DEMO", "Streamlit prediction interface"], ["MODEL OUTPUT", "Healthy / Failure + Failure Probability"]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong><Check size={15} /></div>)}</div><div className="battery-verified"><div><span>VERIFIED INFERENCE EXAMPLE</span><strong>BATTERY FAILURE RISK</strong><b>97.67%</b><small>FAILURE PROBABILITY</small></div><div className="battery-terminal"><span>$ python src/predict.py</span><p>prediction: <b>Failure</b></p><p>failure_probability: <b>0.9767</b></p></div></div><div className="battery-ship-actions"><Button href="/projects/ev-battery-failure/demo">TRY LIVE MODEL <ArrowRight size={15} /></Button><Button href={d.github} secondary>VIEW SOURCE ON GITHUB <ExternalLink size={14} /></Button></div><a className="battery-back" href="/"><ArrowLeft size={14} /> BACK TO PORTFOLIO</a></div></div></section> }

export function EVBatteryFailurePage() { return <main className="battery-case-study"><Header /><article id="main-content"><ProjectHero /><ProblemDataSection /><DataSignalsSection /><MLApproachSection /><ModelComparisonSection /><ResultShipSection /></article></main> }
